# Generated by Django 4.2.16 on 2025-12-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_saved_card'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedcard',
            new_name='payments_sa_tx_id_dab439_idx',
            old_name='payments_s_tx_id_7c6f66_idx',
        ),
        migrations.RenameIndex(
            model_name='savedcard',
            new_name='payments_sa_custome_f2bdaa_idx',
            old_name='payments_s_custom_6d5d64_idx',
        ),
    ]
